[package]
name = "license-updater"
version = "0.0.0"
edition = "2021"
license = "MIT"
repository.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lints]
workspace = true
