[workspace]
members = [
    "td",
    "tendrils",
]

resolver = "2" # Required to use 2 vs 1 to prevent _test_utils
               # being included even outside of testing

[profile.release]
strip = true
lto = true
