[workspace.package]
description = "Manage specific files/folders strewn about the computer from a single location"
license = "GPL-3.0-or-later"
repository = "https://github.com/TendrilApps/tendrils-cli"

[workspace]
members = [
    "td",
    "tendrils",
]
resolver = "2" # Required to use 2 vs 1 to prevent _test_utils
               # being included even outside of testing

[workspace.lints.rustdoc]
broken-intra-doc-links = "forbid"
private-intra-doc-links = "forbid"

[profile.release]
strip = true
lto = true
panic = "abort"
opt-level = "z"
codegen-units = 1
incremental = true
