[package]
name = "tendrils"
version = "0.0.1"
edition = "2018"

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

[profile.release]
strip = true
lto = true
