[package]
name = "tendrils"
version = "0.0.1"
edition = "2018"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
fs_extra = "1.3.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

[dev-dependencies]
serial_test = "2.0.0"
tempdir = "0.3.7"

[profile.release]
strip = true
lto = true
