# Several of these rules require the nightly
# toolchain. Run using "cargo +nightly fmt"

# General
control_brace_style = "ClosingNextLine"
format_code_in_doc_comments = true
match_arm_blocks = true
match_block_trailing_comma = false
newline_style = "Unix"
trailing_comma = "Vertical"
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true

# Width and wrapping
max_width = 80
chain_width = 80
comment_width = 80
fn_call_width = 80
inline_attribute_width = 0
struct_lit_width = 80
struct_variant_width = 80
error_on_line_overflow = false
error_on_unformatted = true
fn_single_line = false
fn_params_layout = "Tall"
format_strings = true
overflow_delimited_expr = true
struct_lit_single_line = true
wrap_comments = true

# Imports and modules
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
group_imports = "One"
