name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-full:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --all-features --verbose --workspace --release
    - name: Check empty tempdir folder
      run: cargo test --all-features --verbose --workspace --release
    - name: Build binary
      run: cargo build --all-features --verbose
    - name: Build docs
      run: cargo doc --all-features --workspace --document-private-items --no-deps --release
