name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-full:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests except admin tests
      # Test all features except _admin_tests
      run: cargo test --workspace --release --features default
    - name: Check tempdir folder is empty
      run: |
        repoFolder=$(git rev-parse --show-toplevel)
        if [ "$(ls $repoFolder/target/tempdirs)" != "" ]; then
          echo "Temp folder is not empty. Test cases may not be cleaning up properly."
          exit 1
        fi
    - name: Build binary
      run: cargo build --all-features
    - name: Build docs
      run: cargo doc --all-features --workspace --document-private-items --no-deps --release
